# Generated by Django 5.2.17 on 2026-09-23 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(help_text='Must match the track.project label on the container.', max_length=80, unique=True)),
                ('dockerfile', models.TextField(blank=True, help_text='Paste the Dockerfile from git or CI. The portal does not read it from the container.')),
                ('members', models.ManyToManyField(blank=True, help_text='These users can open the project. Superusers can open every project.', related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnvName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_set', models.BooleanField(default=False, help_text='Checked when CI reports this variable as present. Store the name only.')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_names', to='monitor.project')),
            ],
            options={
                'verbose_name': 'env name',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='unique_env_name_per_project')],
            },
        ),
    ]
