# Generated by Django 5.2.17 on 2026-09-23 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_demo_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(help_text='Exact Docker container name, such as track-demo.', max_length=255, unique=True)),
                ('dockerfile', models.TextField(blank=True, help_text='Paste the Dockerfile from git or CI. The portal does not read it from the container.')),
            ],
            options={
                'ordering': ['container_name'],
            },
        ),
        migrations.CreateModel(
            name='NoteEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_set', models.BooleanField(default=False, help_text='Checked when CI reports this variable as present. Store the name only.')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_flags', to='monitor.containernote')),
            ],
            options={
                'verbose_name': 'env name',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('note', 'name'), name='unique_note_env_name')],
            },
        ),
        migrations.CreateModel(
            name='UserContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['container_name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'container_name'), name='unique_user_container')],
            },
        ),
    ]
